spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/insurance?serverTimezone=Asia/Seoul
    username: root
    password: ENC(V92yNhCZrv+qKOBh0FE7/g==)

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(Ap/rB2uu0+YHcUvhNBu32hHSD/eyVb3kBwMluMK/NaU=)
    password: ENC(yri9W6DXTLzQgScP+QBiQBiqwF/JaFJ6)
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true